### ISSUE TITLE
Support for hololens/oculus

### ISSUE THREAD

**Issue by emilx-cell** [kikoano/web2vr#13]
Hi,

I can see on the front github page a statement that this project was not tested on oculus.
Did anyone manage to test it on Oculus or Hololens? should there be a problem on those devices?

Thanks for the help and for the very cool project,
EM.

**Comment by kikoano** [comment]
It works on all desktop VR that A-Frame supports. I have tested all the desktop VR tests with my Oculus Rift S. I dont have Standalone VR(android based) like Quest 1 and 2 so I cannot confirm if everything works there.

**Comment by emilx-cell** [comment]
Got it. 
Thanks for the quick answer.
