### ISSUE TITLE
TypeError: Cannot read property 'listeningForMouseEvents' of undefined

### ISSUE THREAD

**Issue by kylebakerio** [kikoano/web2vr#4]
```js
TypeError: Cannot read property 'listeningForMouseEvents' of undefined
    at ContainerElement.update (element.js:185)
    at Web2VR.update (web2vr.js:284)
    at web2vr.js:142
update | @ | web2vr.js:287
-- | -- | --
  | (anonymous) | @ | web2vr.js:142
  | setInterval (async) |   |  
  | allLoadedUpdate | @ | web2vr.js:136
  | init | @ | web2vr.js:131
  | start | @ | web2vr.js:117
  | (anonymous) | @ | ?NAFopts={"app":"vrg…pter":"easyRTC"}:57
```
Admittedly, I'm surely doing something wrong that's my fault, however the examples are all too complex to draw from. The very basic 'hello world' example you give, on the other hand, doesn't show an `<a-scene>` present, and so it is unclear how to integrate that.

This stack trace isn't helpful for me, unfortunately--I don't see listeningForMouseEvents referred to at all, which is confusing.

I'm really excited about this library and want to use it! Please help point me in the right direction. I saw that you don't have a quest to test on--I'll be getting a quest 2 soon and I'll be glad to help with that.

**Comment by kylebakerio** [comment]
I just noticed that the basic demo actually produces this error message even when it works correctly, it seems, so this is likely not my problem--I just have to figure out how to get the render into my scene...?

(to be clear: I was using aframe 1.1.0, which produced more errors, but the error described above is when I rolled back to aframe 1.0.4 explicitly to try this repo.)

https://deciduous-cooing-error.glitch.me/old-aframe

**Comment by kylebakerio** [comment]
Just noticed that when trying to add the demo to my app, it also breaks `movement-controls` from`aframe-extras`.  Hoping that's just my own bad attempt at implementation somehow.

**Comment by kikoano** [comment]
If you use web2vr on aframe 1.1.0 right now everything will break. You will have to use aframe 1.0.4 for now. Working on new update that will support aframe 1.1.0.

**Comment by kylebakerio** [comment]
I just want to add here that I saw github swallowed a critical thing I wrote above with misinterpreted markdown, so I'll repeat it just to make sure you see:

> The very basic 'hello world' example you give, on the other hand, doesn't show an <a-scene> present, and so it is unclear how to integrate that.

I would love to see an example showing how to do that a little more clearly / approachably.
