### ISSUE TITLE
VR keyboard on input demo allows arrowkey pass through

### ISSUE THREAD

**Issue by kylebakerio** [kikoano/web2vr#8]
The input demo/test looks really great, but I noticed that when I hit arrowup/arrowdown, that ArrowUp, etc., went into the text input field, instead of me being able to move the text cursor around (more advanced but optimal) or just move around (easier, more straightforward implementation).

**Comment by kikoano** [comment]
Never noticed that because I always moved with WASD on desktop. Will disable them in next update. This cannot happen while you are in VR.

**Comment by kylebakerio** [comment]
It might if a bluetooth keyboard is connected, as they can be in the quest, and in the future will be on the quest 2.

**Comment by kikoano** [comment]
Will be fixed in the upcoming update.
