### ISSUE TITLE
Reactive elements create duplicate entities on re-render

### ISSUE THREAD

**Issue by mattrossman** [kikoano/web2vr#9]
I tried building a simple UI using preact and connecting it to web2vr:

https://glitch.com/~mercury-veil-newsprint

When the text is clicked, a new piece of text is created next to the old one instead of the old one updating, which compounds into a huge chunk of text.

**Comment by kikoano** [comment]
It doesnt support React because React virtual dom works bit different.

**Comment by kikoano** [comment]
I will start working to make Web2VR work with React.
